### ISSUE TITLE
AccessDenied: This request is not authorized by the specified access token

### ISSUE THREAD

**Issue by davidhpark** [dpjanes/iotdb-smartthings#20]
I'm having issues with the access token.

$ python smartthings.py --type battery
Traceback (most recent call last):
  File "smartthings.py", line 209, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 119, in request_devices
    SmartThings.raise_api_errors(self.deviceds)
  File "smartthings.py", line 55, in raise_api_errors
    raise Exception(error_type + ": " + error_message)
Exception: AccessDenied: This request is not authorized by the specified access token

**Comment by davidhpark** [comment]
Nevermind. Fixed! Was an issue with the URL hardcoded into the JSON.
