### ISSUE TITLE
TypeError: data must be a byte string

### ISSUE THREAD

**Issue by poblabs** [dpjanes/iotdb-smartthings#5]
Getting this error when trying to get a simple device listing. I've got the IOTDB JSON output into a `smartthings.json` file in the same directory as `smartthings.py`, but it seems there's an error. Thoughts?

```
]$ sudo python smartthings.py --type=switch
Traceback (most recent call last):
  File "smartthings.py", line 167, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 88, in request_devices
    devices_response = requests.get(url=devices_url, params=devices_paramd, headers=devices_headerd)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.6/httplib.py", line 936, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 973, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 930, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 802, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 781, in send
    self.sock.sendall(str)
  File "/usr/lib/python2.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 225, in sendall
    sent = self._send_until_done(data)
  File "/usr/lib/python2.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 215, in _send_until_done
    return self.connection.send(data)
  File "/usr/lib/python2.6/site-packages/OpenSSL/SSL.py", line 947, in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
```

**Comment by dpjanes** [comment]
It may be that you are using Python 2.6 (released in 2008!) - developed using Python 2.7. That would be the first thing I would check against.

**Comment by poblabs** [comment]
You're right, I'm on CentOS 6.7 which has Python 2.6.6. Guess I'll need to see how to upgrade to 2.7 without breaking yum. 

Also, I can't find the OAuth settings in the IOTDB dashboard in my account anywhere. Is that by design?

**Comment by poblabs** [comment]
Python 2.7 on my Raspberry Pi worked great.

**Comment by dpjanes** [comment]
You can compile Python from source on your CentOS box and configure with --prefix=$HOME/local. That's what I do, but I'm oldschool
