### ISSUE TITLE
Smartthings update broke it

### ISSUE THREAD

**Issue by BluGeni** [dpjanes/iotdb-smartthings#6]
seems after an ST update nothing seems to work. I just get this error:

pi@raspberrypi ~/iotdb-smartthings $ python smartthings.py --type switch
Traceback (most recent call last):
  File "smartthings.py", line 165, in <module>
    st.request_endpoints()
  File "smartthings.py", line 69, in request_endpoints
    self.endpointd = endpoints_response.json()[0]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by dpjanes** [comment]
Is it just a general "SmartThings is not up" problem? This URL is not responding
https://graph.api.smartthings.com/

**Comment by BluGeni** [comment]
Nevermind, it seems to have cleared up. Not sure if it was hub or what but I didnt change anything and its working again after just leaving it for a couple hours.

**Comment by dpjanes** [comment]
I think it was SmartThings. I saw the error too, and then saw it get fixed
up. Why I don't like Cloud-based IoT.
