### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by jiribrejcha** [dpjanes/iotdb-smartthings#7]
Hi, after following your Readme instructions, I am getting these errors. Could you please help me fix them?

JIBREJCH:smartthings jibrejch$ python smartthings.py --type motion
Traceback (most recent call last):
  File "smartthings.py", line 167, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 91, in request_devices
    switchd['url'] = "%s/%s" % ( devices_url, switchd['id'], )

Many thanks,
Jiri

**Comment by dpjanes** [comment]
Make sure the app can see the devices. Sometimes this takes a little
playing around the SmartThings app.

**Comment by timh5** [comment]
fyi ... i got the same issues and that was because i copy pasted the code directly into terminal, and it didn't preserve the tabs.... i had to reindent.
