### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by ChristopherRios7** [dpjanes/iotdb-smartthings#8]
This is the error that I am getting:

Traceback (most recent call last):
  File "smartthings.py", line 148, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 72, in request_devices
    switchd['url'] = "%s/%s" % (devices_url, switchd['id'],)
TypeError: string indices must be integers

**Comment by dpjanes** [comment]
Is it that the app hasn't been authorized to see this device yet?

**Comment by jacobbraun** [comment]
I had to change the URL in the python code from "graph.api.smartthings.com" to "https://graph-na02-useast1.api.smartthings.com" and that fixed the same error for me.

**Comment by dpjanes** [comment]
How did you come up with that URL?

**Comment by jacobbraun** [comment]
It's the one I log into. I'm a relatively new (three or so months) user and I've been out on a different t server

**Comment by dpjanes** [comment]
Any suggestions on how I should deal with this? Allow for an optional URL
in the smarthings.json ?

**Comment by drajen** [comment]
Could we file a ticket with SmartThings to understand their intent is and design around what answers they may provide?

**Comment by dpjanes** [comment]
Can you do that, since I'm not actually experiencing the issue?

**Comment by tomowad** [comment]
I ran into this issue as well, and the same fix worked.

**Comment by tomowad** [comment]
Here's some more information that addresses the differences in URLs: https://community.smartthings.com/t/faq-how-to-find-out-what-shard-cloud-slice-ide-url-your-account-location-is-on/53923

**Comment by dpjanes** [comment]
Thank you all. I will work on a fix for this.
